dh_params:
  joint0:
    # DH parameter for base frame to intermdiate joint frame
    theta: 1.5708
    alpha: 1.5708
    a: 0.0
    d: 0.0
  joint0.5:
    # Inserted joint0.5 as an intermediate frame since direct DH transformation from joint0 to joint1 is not feasible.
    # DH parameter for intermediate motor frame to shoulder motor frame (intermediate joint)
    theta: 0
    alpha: 0
    a: 0.0
    d: 0.1
  joint1:  # DH parameter for shoulder motor frame to arm motor frame  
    alpha: -1.5708
    a: 0
    d: 0.23
  joint2:  # DH parameter for arm motor frame to elbow motor frame  
    alpha: 0
    a: 0.3
    d: 0.0
  joint3:  # DH parameter for elbow motor frame to ee frame
    alpha: 0
    a: 0.47
    d: 0.0
