dh_params:
  joint1:  # DH parameter for shoulder motor frame to arm motor frame  
    alpha: 90
    a: 0
    d: 0.23
  joint2:  # DH parameter for arm motor frame to elbow motor frame  
    alpha: 0
    a: 0.3
    d: 0
  joint3:  # DH parameter for elbow motor frame to ee frame
    alpha: 0
    a: 0.3
    d: 0
